python3Packges.websocket: add missing six dependency
```
       > Processing ./websocket_client-0.56.0-py2.py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement six (from websocket-client) (from versions: none)
       > ERROR: No matching distribution found for six
       >
```